Repository ipfs/ipfs-cluster, pull requests merged in 2018-10, with the labels that each got.

#559 Fix #544: Push Snaps to the right channel depending on tags
  .travis.yml
Labels: in progress

#560 Fix #548: Re-enable keep-alives. Set Connection: Close when adding.
  adder/adderutils/adderutils.go
  api/rest/restapi.go
  ipfsconn/ipfshttp/ipfshttp.go
Labels: in progress

#558 Update to go-1.11
  .travis.yml
  Dockerfile
  Dockerfile-test
  package.json
  snap/snapcraft.yaml
Labels: in progress

#561 api/rest: change *cid.Cid to cid.Cid in client iface
  api/rest/client/client.go
  api/rest/client/methods.go
  api/rest/client/methods_test.go
  cmd/ipfs-cluster-ctl/main.go
Labels: in progress, needs review, priority:high

#562 Snap build fixes. Re-enable multiarch builds.
  .travis.yml
  snap/snap-multiarch.sh
  snap/snapcraft.yaml
Labels: in progress

#565 Fix: snaps for tags
  .travis.yml
Labels: in progress

#564 Fix IPFS() method missing in Client interface
  api/rest/client/client.go
Labels: in progress

#567 Docs: Fix comment for WaitFor function
  api/rest/client/methods.go
Labels: in progress

#570 ipfshttp: remove custom proxy and use stdlib reverse proxy
  ipfsconn/ipfshttp/ipfshttp.go
Labels: in progress

#569 Add endpoints output: improvements and compliance
  adder/adderutils/adderutils.go
  adder/ipfsadd/add.go
  adder/sharding/dag_service.go
  adder/sharding/dag_service_test.go
  api/add.go
  api/rest/client/methods.go
  api/rest/client/methods_test.go
  api/rest/client/request.go
  api/rest/restapi.go
  cmd/ipfs-cluster-ctl/formatters.go
  cmd/ipfs-cluster-ctl/main.go
  ipfsconn/ipfshttp/ipfshttp.go
  ipfsconn/ipfshttp/ipfshttp_test.go
Labels: in progress, needs review

#578 Restapi: Add configurable response headers
  api/rest/config.go
  api/rest/restapi.go
  api/rest/restapi_test.go
  config_test.go
Labels: in progress

#573 Pubsubmon: Gossipsub
  monitor/pubsubmon/pubsubmon.go
  monitor/pubsubmon/pubsubmon_test.go
Labels: in progress

#580 Upgrade to libp2p-6.0.19. Update deps.
  .travis.yml
  adder/adderutils/adderutils.go
  adder/local/dag_service.go
  adder/local/dag_service_test.go
  adder/sharding/dag.go
  adder/sharding/dag_service.go
  adder/sharding/dag_service_test.go
  adder/sharding/shard.go
  adder/util.go
  allocator/ascendalloc/ascendalloc.go
  allocator/descendalloc/descendalloc.go
  api/rest/client/methods_test.go
  api/rest/restapi.go
  cluster.go
  cluster_test.go
  cmd/ipfs-cluster-ctl/graph_test.go
  consensus/raft/consensus.go
  informer/disk/disk.go
  informer/disk/disk_test.go
  informer/numpin/numpin.go
  informer/numpin/numpin_test.go
  ipfscluster.go
  ipfsconn/ipfshttp/ipfshttp.go
  monitor/basic/peer_monitor.go
  monitor/pubsubmon/pubsubmon.go
  package.json
  pintracker/maptracker/maptracker.go
  pintracker/maptracker/maptracker_test.go
  pintracker/pintracker_test.go
  pintracker/stateless/stateless.go
  pintracker/stateless/stateless_test.go
  test/rpc_api_mock.go
Labels: in progress

#583 Fix: escape the add query parameters correctly in the client
  api/add.go
  api/rest/client/methods_test.go
Labels: in progress

#581 Fix #577: Try downloading gx and gx-go from local ipfs gateway first
  .gitignore
  Makefile
  deptools/Makefile
Labels: in progress

#572 Issue #449 API endpoint for Peer Monitor metrics
  api/rest/client/client.go
  api/rest/client/methods.go
  api/rest/restapi.go
  cmd/ipfs-cluster-ctl/formatters.go
  cmd/ipfs-cluster-ctl/main.go
Labels: in progress

#586 Fix: escape filter parameter query
  api/rest/client/methods.go
Labels: in progress

#590 Files package has been extracted from cmdkit
  adder/adder.go
  adder/ipfsadd/add.go
  api/rest/client/client.go
  api/rest/client/methods.go
  ipfsconn/ipfshttp/ipfshttp.go
  package.json
  test/sharding.go
Labels: in progress

#592 Upgrade to libp2p 6.0.23
  package.json
Labels: in progress

#594 Fix publishing snaps
  .travis.yml
  snap/snapcraft.yaml
Labels: in progress

#595 Fix tests with latest libp2p
  api/rest/client/client_test.go
  consensus/raft/consensus_test.go
  ipfscluster_test.go
  peer_manager_test.go
Labels: in progress

#589 Make metrics human
  api/rest/client/methods.go
  api/rest/client/request.go
  api/types.go
  cluster.go
  cmd/ipfs-cluster-ctl/formatters.go
  cmd/ipfs-cluster-ctl/main.go
  monitor/metrics/store.go
  monitor/metrics/util.go
  rpc_api.go
Labels: in progress

#598 Upgrade ipld-related dependencies. Remove importers DAG forced-Batching.
  adder/ipfsadd/add.go
  package.json
Labels: in progress

#596 add env config; refactor LoadJSON tests
  cluster_config.go
  cluster_config_test.go
  package.json
Labels: in progress, needs review

#599 Update to latest go-libp2p-pubsub (with renames)
  monitor/pubsubmon/pubsubmon.go
  monitor/pubsubmon/pubsubmon_test.go
  package.json
Labels: in progress

#601 Feat/improve pin serial
  api/types.go
  api/types_test.go
  consensus/raft/log_op.go
  rpc_api.go
Labels: in progress
