Repository ipfs/ipfs-cluster, pull requests merged in 2018-09, with the labels that each got.

#537 gx update go-dot
  ipfs-cluster-ctl/graph.go
  package.json
Labels: in progress, needs review

#542 Issue #536 New make target for PR check
  Makefile
Labels: RFM

#529 speed up building docker image
  .gitignore
  Dockerfile
  Makefile
Labels: RFM

#544 update go-cid and go-libp2p
  adder/adder.go
  adder/adder_test.go
  adder/adderutils/adderutils.go
  adder/ipfsadd/add.go
  adder/local/dag_service.go
  adder/sharding/dag.go
  adder/sharding/dag_service.go
  adder/sharding/dag_service_test.go
  adder/sharding/shard.go
  adder/sharding/verify.go
  adder/util.go
  allocate.go
  allocator/ascendalloc/ascendalloc.go
  allocator/descendalloc/descendalloc.go
  api/rest/client/methods.go
  api/types.go
  cluster.go
  cluster_test.go
  consensus/raft/consensus_test.go
  ipfs-cluster-ctl/main.go
  ipfscluster.go
  ipfsconn/ipfshttp/ipfshttp.go
  package.json
  peer_manager_test.go
  pintracker/maptracker/maptracker.go
  pintracker/maptracker/maptracker_test.go
  pintracker/optracker/operation.go
  pintracker/optracker/operationtracker.go
  pintracker/pintracker_test.go
  pintracker/stateless/stateless.go
  pintracker/stateless/stateless_test.go
  state/interface.go
  state/mapstate/map_state.go
  test/cids.go
  util.go
Labels: in progress

#550 Fix #520 snapcraft stages
  .travis.yml
Labels: in progress

#551 Allow running peers with different cluster versions in the same cluster
  cluster.go
  cluster_test.go
  ipfs-cluster-service/main.go
  ipfscluster.go
  ipfscluster_test.go
  package.json
  release.sh
  version.go
Labels: in progress

#549 Fix #543: Use only healthy peers when adding everywhere (+tests)
  add_test.go
  cluster.go
  rpc_api.go
Labels: in progress

#556 Move `ipfs-cluster-service` and `ipfs-cluster-ctl` to `cmd/`
  .gitignore
  Makefile
  cmd/ipfs-cluster-ctl/Makefile
  cmd/ipfs-cluster-ctl/dist/LICENSE
  cmd/ipfs-cluster-ctl/dist/README.md
  cmd/ipfs-cluster-ctl/formatters.go
  cmd/ipfs-cluster-ctl/graph.go
  cmd/ipfs-cluster-ctl/graph_test.go
  cmd/ipfs-cluster-ctl/main.go
  cmd/ipfs-cluster-service/Makefile
  cmd/ipfs-cluster-service/configs.go
  cmd/ipfs-cluster-service/daemon.go
  cmd/ipfs-cluster-service/dist/LICENSE
  cmd/ipfs-cluster-service/dist/README.md
  cmd/ipfs-cluster-service/lock.go
  cmd/ipfs-cluster-service/main.go
  cmd/ipfs-cluster-service/state.go
Labels: in progress

#555 fix make test: the make test rule should not pass the -loglevel flag
  Makefile
Labels: in progress
