Repository ipfs/ipfs-cluster, pull requests merged in 2018-05, with the labels that each got.

#392 ipfsconn/ipfshttp: handle cid args passed in url path correctly
  ipfsconn/ipfshttp/ipfshttp.go
  ipfsconn/ipfshttp/ipfshttp_test.go
  test/ipfs_mock.go
Labels: RFM, in progress

#393 Docs/move to website
  CAPTAIN.LOG.md
  CONTRIBUTING.md
  README.md
  ROADMAP.md
  architecture.md
  contribute.md
  docs/HOWTO_build_and_update_a_cluster.md
  docs/dag-sharding-rfc.md
  docs/developer-certificate-of-origin
  docs/ipfs-cluster-guide.md
  ipfs-cluster-ctl/dist/README.md
  ipfs-cluster-service/dist/README.md
Labels: in progress

#386 Tests to front end of adding pipeline
  Makefile
  add/add.go
  api/rest/client/methods.go
  api/rest/client/methods_test.go
  api/rest/client/request.go
  api/rest/config.go
  api/rest/restapi.go
  api/rest/restapi_test.go
  api/types.go
  cluster.go
  cluster_test.go
  importer/import.go
  importer/import_test.go
  importer/testingData/A/alpha/contents-overview.txt
  importer/testingData/A/beta/lorem-ipsum-explained.io
  importer/testingData/A/delta/empty/.gitignore
  importer/testingData/A/file.txt
  importer/testingData/A/gamma/don-quixote.txt
  importer/testingData/B/emerson-essays.txt
  importer/testingData/B/poor-richard.txt
  ipfs-cluster-ctl/files.go
  ipfs-cluster-ctl/formatters.go
  ipfs-cluster-ctl/main.go
  ipfs-cluster-service/main.go
  ipfscluster.go
  ipfscluster_test.go
  ipfsconn/ipfshttp/config.go
  ipfsconn/ipfshttp/ipfshttp.go
  ipfsconn/ipfshttp/ipfshttp_test.go
  rpc_api.go
  sharder/sharder.go
  sharder/sharder_test.go
  sharness/t0031-ctl-add.sh
  sharness/test_data/small_file
  test/cids.go
  test/ipfs_mock.go
  test/rpc_api_mock.go
  test/test_files.go
  test/test_test.go
Labels: in progress

#383 Feat: pintracker revamp
  allocate.go
  allocator/descendalloc/descendalloc.go
  api/types.go
  cluster_test.go
  config_test.go
  ipfscluster.go
  ipfscluster_test.go
  ipfsconn/ipfshttp/config.go
  ipfsconn/ipfshttp/config_test.go
  ipfsconn/ipfshttp/ipfshttp.go
  ipfsconn/ipfshttp/ipfshttp_test.go
  peer_manager_test.go
  pintracker/maptracker/config.go
  pintracker/maptracker/config_test.go
  pintracker/maptracker/maptracker.go
  pintracker/maptracker/maptracker_test.go
  pintracker/maptracker/operationtracker.go
  pintracker/maptracker/operationtracker_test.go
  pintracker/maptracker/operationtype_string.go
  pintracker/maptracker/phase_string.go
  rpc_api.go
  test/cids.go
Labels: RFM

#398 Emancipate the consensus component
  .gitignore
  Dockerfile-test
  Makefile
  api/rest/restapi.go
  cluster.go
  cluster_config.go
  cluster_config_test.go
  cluster_test.go
  config_test.go
  consensus/raft/config.go
  consensus/raft/config_test.go
  consensus/raft/consensus.go
  consensus/raft/consensus_test.go
  consensus/raft/data_helper.go
  consensus/raft/data_helper_test.go
  consensus/raft/raft.go
  ipfs-cluster-service/configs.go
  ipfs-cluster-service/daemon.go
  ipfs-cluster-service/main.go
  ipfs-cluster-service/state.go
  ipfscluster.go
  ipfscluster_test.go
  peer_manager.go
  peer_manager_test.go
  pstoremgr/pstoremgr.go
  pstoremgr/pstoremgr_test.go
  rpc_api.go
  sharness/config/basic_auth/service.json
  sharness/config/ssl-basic_auth/service.json
  sharness/config/ssl/service.json
  sharness/lib/test-lib.sh
Labels: in progress

#402 Tests of new pin types
  cluster_test.go
  test/cids.go
Labels: in progress

#415 Fix #408: Race condition when StateSync runs
  ipfscluster_test.go
  pintracker/maptracker/maptracker.go
Labels: in progress, needs review

#417 Fix: some govet warnings
  api/rest/config.go
  ipfsconn/ipfshttp/config.go
  pstoremgr/pstoremgr.go
Labels: in progress

#420 Set refs as default pinning method, with 10 parallel pins
  ipfsconn/ipfshttp/config.go
  pintracker/maptracker/config.go
Labels: RFM

#427 ipfshttp: Use custom http clients for pin/unpin
  ipfsconn/ipfshttp/ipfshttp.go
Labels: in progress

#430 Fix/data folder
  consensus/raft/config.go
  consensus/raft/raft.go
  sharness/lib/test-lib.sh
  sharness/t0051-service-state-upgrade-from-old.sh
Labels: in progress

#429 StateSync(): some improvements
  cluster.go
  cluster_test.go
  ipfs-cluster-service/daemon.go
  rpc_api.go
  test/rpc_api_mock.go
Labels: in progress

#440 Go-libp2p: update to 5.0.17
  package.json
Labels: in progress

#439 Test with Go 1.10
  .travis.yml
  coverage.sh
Labels: in progress

#432 Fix: maptracker data-race issues
  allocate.go
  api/types.go
  cluster.go
  ipfscluster_test.go
  pintracker/maptracker/maptracker.go
  pintracker/maptracker/maptracker_test.go
  pintracker/maptracker/operationtracker.go
  pintracker/maptracker/operationtracker_test.go
  pintracker/maptracker/operationtype_string.go
  pintracker/maptracker/phase_string.go
  pintracker/optracker/operation.go
  pintracker/optracker/operation_test.go
  pintracker/optracker/operationtracker.go
  pintracker/optracker/operationtracker_test.go
  pintracker/optracker/operationtype_string.go
  pintracker/optracker/phase_string.go
  pintracker/util/pin.go
  rpc_api.go
  test/cids.go
  util.go
Labels: in progress, needs review

#443 Fix #433: Use new floodsub version
  package.json
Labels: in progress

#442 Fix #412: Add an issue template
  .github/ISSUE_TEMPLATE.md
Labels: in progress
