Repository ipfs/ipfs-cluster, pull requests merged in 2019-02, with the labels that each got.

#659 Fix/update json config
  config/config.go
  config/config_test.go
Labels: bug, in progress, needs review, priority:high

#649 Fix #593: Remove snaps
  .snapcraft/travis_snapcraft.cfg
  .travis.yml
  snap/snap-multiarch.sh
  snap/snapcraft.yaml
Labels: RFM

#674 bring pprof urls in line with default
  observations/setup.go
Labels: in progress

#671 Rename observations Config fields
  observations/config.go
  observations/setup.go
Labels: in progress

#676 Fix context cancelled too early.
  ipfsconn/ipfshttp/ipfshttp.go
Labels: in progress

#664 v0.9.0 changelog
  CHANGELOG.md
Labels: in progress

#677 Release 0.9.0
  .gx/lastpubver
  cmd/ipfs-cluster-ctl/main.go
  package.json
  version/version.go
Labels: in progress

#675 Dependency alignment for libp2p-6.0.33, dag libraries and others
  adder/ipfsadd/add.go
  cluster.go
  consensus/raft/raft.go
  package.json
Labels: RFM, in progress

#679 Update to libp2p-6.0.35 and general dep alignment
  package.json
Labels: in progress

#663 Read config values from env on init command
  api/ipfsproxy/config.go
  api/ipfsproxy/config_test.go
  api/rest/config.go
  api/rest/config_test.go
  cluster_config.go
  cluster_config_test.go
  cmd/ipfs-cluster-service/daemon.go
  cmd/ipfs-cluster-service/main.go
  cmd/ipfs-cluster-service/state.go
  config/config.go
  config/config_test.go
  consensus/raft/config.go
  consensus/raft/config_test.go
  informer/disk/config.go
  informer/disk/config_test.go
  informer/numpin/config.go
  informer/numpin/config_test.go
  ipfsconn/ipfshttp/config.go
  ipfsconn/ipfshttp/config_test.go
  monitor/basic/config.go
  monitor/basic/config_test.go
  monitor/pubsubmon/config.go
  monitor/pubsubmon/config_test.go
  observations/config.go
  observations/config_test.go
  pintracker/maptracker/config.go
  pintracker/maptracker/config_test.go
  pintracker/stateless/config.go
  pintracker/stateless/config_test.go
Labels: in progress

#680 make tracing service name unique
  cmd/ipfs-cluster-service/configs.go
  observations/config.go
  observations/setup.go
Labels: in progress

#655 State: Use go-datastore to implement the state interface
  api/pb/types.pb.go
  api/pb/types.proto
  api/types.go
  api/types_test.go
  cluster.go
  cmd/ipfs-cluster-service/state.go
  consensus/raft/consensus_test.go
  consensus/raft/log_op.go
  state/dsstate/datastore.go
  state/interface.go
  state/mapstate/map_state.go
  state/mapstate/map_state_test.go
  state/mapstate/migrate.go
  test/ipfs_mock.go
Labels: in progress

#683 Move to codecov.io
  .travis.yml
  README.md
Labels: in progress

#682 Remove backwards compatibility hacks
  api/ipfsproxy/config.go
  api/rest/client/client.go
  api/rest/config.go
  api/types.go
  cluster_config.go
  cluster_config_test.go
  config/config.go
  consensus/raft/raft.go
  ipfsconn/ipfshttp/config.go
Labels: in progress

#681 New options in PinOptions
  api/pb/types.pb.go
  api/pb/types.proto
  api/types.go
  api/types_test.go
Labels: in progress, needs review

#647 API: Allow user to set peer allocations for pinning
  api/rest/client/methods_test.go
  api/rest/restapi_test.go
  cluster.go
  cmd/ipfs-cluster-ctl/main.go
  sharness/t0030-ctl-pin.sh
Labels: RFM, blocked, in progress

#686 Update libp2p et al. ..... again
  package.json
Labels: in progress

#687 Update libp2p to 6.0.38
  package.json
Labels: in progress
