Repository ipfs/ipfs-cluster, pull requests merged in 2019-05, with the labels that each got.

#768 Proxy: hijack pin/update
  api/ipfsproxy/ipfsproxy.go
  api/ipfsproxy/ipfsproxy_test.go
  ipfsconn/ipfshttp/ipfshttp.go
  rpc_api.go
  test/rpc_api_mock.go
Labels: in progress

#767 Types: make UserAllocations []peer.ID instead of string
  api/ipfsproxy/ipfsproxy.go
  api/ipfsproxy/ipfsproxy_test.go
  api/rest/client/methods_test.go
  api/rest/restapi_test.go
  api/types.go
  api/types_test.go
  cluster.go
  cmd/ipfs-cluster-ctl/main.go
  ipfsconn/ipfshttp/ipfshttp.go
  rpc_api.go
  test/rpc_api_mock.go
Labels: in progress

#773 RPC: Give each component a different RPC Service
  adder/local/dag_service.go
  adder/local/dag_service_test.go
  adder/sharding/dag.go
  adder/sharding/dag_service_test.go
  adder/util.go
  api/ipfsproxy/ipfsproxy.go
  api/rest/restapi.go
  cluster.go
  connect_graph.go
  consensus/crdt/consensus.go
  consensus/raft/consensus.go
  consensus/raft/log_op.go
  informer/disk/disk.go
  informer/disk/disk_test.go
  informer/numpin/numpin.go
  informer/numpin/numpin_test.go
  ipfscluster.go
  pintracker/maptracker/maptracker.go
  pintracker/maptracker/maptracker_test.go
  pintracker/pintracker_test.go
  pintracker/stateless/stateless.go
  pintracker/stateless/stateless_test.go
  rpc_api.go
  test/rpc_api_mock.go
  test/test_test.go
Labels: needs review

#766 Separate Identity and Configuration
  cluster_config.go
  cluster_config_test.go
  cluster_test.go
  clusterhost.go
  cmd/ipfs-cluster-service/configs.go
  cmd/ipfs-cluster-service/daemon.go
  cmd/ipfs-cluster-service/main.go
  cmd/ipfs-cluster-service/state.go
  config/config.go
  config/identity.go
  config/identity_test.go
  config_test.go
  ipfscluster_test.go
  peer_manager_test.go
  sharness/config/basic_auth/identity.json
  sharness/config/basic_auth/service.json
  sharness/config/ssl-basic_auth/identity.json
  sharness/config/ssl-basic_auth/service.json
  sharness/config/ssl/identity.json
  sharness/lib/test-lib.sh
Labels: needs review

#775 Feat: RPC Authorization
  api/ipfsproxy/ipfsproxy.go
  api/util.go
  cluster.go
  cluster_config.go
  config_test.go
  consensus/crdt/config.go
  consensus/crdt/config_test.go
  consensus/crdt/consensus.go
  consensus/crdt/consensus_test.go
  consensus/raft/consensus.go
  ipfscluster.go
  ipfscluster_test.go
  peer_manager_test.go
  pnet_test.go
  rpc_api.go
  rpc_policy.go
  rpcutil/policygen/policygen.go
  test/rpc_api_mock.go
Labels: needs review

#714 Monitoring and re-allocation revamp: Accrual failure detection
  api/types.go
  cluster.go
  cluster_test.go
  cmd/ipfs-cluster-service/daemon.go
  config_test.go
  go.mod
  go.sum
  informer/numpin/config_test.go
  ipfscluster_test.go
  ipfsconn/ipfshttp/ipfshttp.go
  monitor/metrics/checker.go
  monitor/metrics/checker_test.go
  monitor/metrics/prob.go
  monitor/metrics/prob_test.go
  monitor/metrics/store.go
  monitor/metrics/window.go
  monitor/metrics/window_test.go
  monitor/pubsubmon/config.go
  monitor/pubsubmon/config_test.go
  monitor/pubsubmon/pubsubmon.go
  monitor/pubsubmon/pubsubmon_test.go
  observations/metrics.go
  observations/setup.go
  pintracker/maptracker/config.go
  pintracker/optracker/operation.go
  pintracker/optracker/operationtracker.go
  pintracker/optracker/operationtype_string.go
  pintracker/optracker/phase_string.go
Labels: in progress

#713 Change the underlying data structure of a metrics.Window
  api/types.go
  cluster.go
  cluster_test.go
  cmd/ipfs-cluster-service/daemon.go
  config_test.go
  go.mod
  go.sum
  informer/numpin/config_test.go
  ipfscluster_test.go
  ipfsconn/ipfshttp/ipfshttp.go
  monitor/metrics/checker.go
  monitor/metrics/checker_test.go
  monitor/metrics/prob.go
  monitor/metrics/prob_test.go
  monitor/metrics/store.go
  monitor/metrics/window.go
  monitor/metrics/window_test.go
  monitor/pubsubmon/config.go
  monitor/pubsubmon/config_test.go
  monitor/pubsubmon/pubsubmon.go
  monitor/pubsubmon/pubsubmon_test.go
  observations/metrics.go
  observations/setup.go
  pintracker/maptracker/config.go
  pintracker/optracker/operation.go
  pintracker/optracker/operationtracker.go
  pintracker/optracker/operationtype_string.go
  pintracker/optracker/phase_string.go
Labels: in progress

#780 service: multiple fixes around init and identities
  cmd/ipfs-cluster-service/configs.go
  cmd/ipfs-cluster-service/lock.go
  cmd/ipfs-cluster-service/main.go
  config/identity.go
Labels: needs review

#502 Fix #340: Run tests with -race
  .travis.yml
  Makefile
  add_test.go
  cluster.go
  cluster_config.go
  cluster_test.go
  clusterhost.go
  config_test.go
  consensus/crdt/consensus.go
  ipfscluster_test.go
  peer_manager_test.go
  pnet_test.go
Labels: blocked, in progress
