Repository ipfs/ipfs-cluster, pull requests merged in 2019-01, with the labels that each got.

#626 Fix ipfs-cluster-ctl with HTTPs multiaddresses
  api/rest/client/client.go
  api/rest/client/client_test.go
Labels: in progress

#622 Added tests for /monitor/metrics/{metrics_type}
  api/rest/client/methods_test.go
  api/rest/restapi_test.go
  api/types.go
  sharness/lib/test-lib.sh
  sharness/t0025-ctl-status-report-commands.sh
  sharness/t0032-ctl-health.sh
Labels: in progress, needs review

#633 Feat/632: support stream-channels query parameter when adding
  adder/adderutils/adderutils.go
  api/add.go
  api/rest/client/methods.go
  api/rest/client/methods_test.go
  api/rest/restapi_test.go
  cmd/ipfs-cluster-ctl/main.go
Labels: in progress

#637 Fix #632: Add --no-stream to ipfs-cluster-ctl
  cmd/ipfs-cluster-ctl/formatters.go
  cmd/ipfs-cluster-ctl/main.go
Labels: in progress

#641 Sharness: update configuration files used in sharness
  api/rest/config.go
  api/rest/config_test.go
  api/rest/restapi.go
  api/rest/restapi_test.go
  package.json
  sharness/config/basic_auth/service.json
  sharness/config/ssl-basic_auth/service.json
  sharness/config/ssl/service.json
Labels: blocked, in progress

#638 Fix #382 (again): A better strategy for handling proxy headers
  api/ipfsproxy/config.go
  api/ipfsproxy/config_test.go
  api/ipfsproxy/headers.go
  api/ipfsproxy/ipfsproxy.go
  api/ipfsproxy/ipfsproxy_test.go
  package.json
  test/ipfs_mock.go
  test/rpc_api_mock.go
Labels: P1 - High, in progress

#642 config: Fix confusing errors
  config/config.go
  config/util.go
Labels: in progress

#643 sharness: Fix test typo causing an empty grep
  sharness/t0032-ctl-health.sh
Labels: in progress

#644 Changelog for 0.8.0 release
  CHANGELOG.md
Labels: in progress
